# Generated by Django 6.0.4 on 2026-05-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mfachallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("register", "Register"),
                    ("password_reset", "Password Reset"),
                    ("reactivate", "Reactivate"),
                ],
                max_length=30,
            ),
        ),
    ]
