# Generated by Django 6.0.4 on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_administratorprofile_driverprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="administratorprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delegated_admins",
                to="users.administratorprofile",
            ),
        ),
        migrations.AddField(
            model_name="administratorprofile",
            name="level",
            field=models.CharField(
                choices=[("superadmin", "Superadmin"), ("subadmin", "Subadmin")],
                default="subadmin",
                max_length=20,
            ),
        ),
    ]
