# Generated by Django 6.0.4 on 2026-05-06

import os

from django.contrib.auth.hashers import make_password
from django.db import migrations


def seed_initial_superadmin(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    AdministratorProfile = apps.get_model("users", "AdministratorProfile")

    if AdministratorProfile.objects.filter(level="superadmin").exists():
        return

    email = os.getenv("SEED_SUPERADMIN_EMAIL", "superadmin@easyrota.local").strip().lower()
    full_name = os.getenv("SEED_SUPERADMIN_NAME", "Super Admin").strip()
    password = os.getenv("SEED_SUPERADMIN_PASSWORD", "admin12345")

    user, created = CustomUser.objects.get_or_create(
        email=email,
        defaults={
            "full_name": full_name,
            "is_active": True,
            "is_staff": True,
            "is_superuser": True,
        },
    )

    update_fields = []
    if user.full_name != full_name:
        user.full_name = full_name
        update_fields.append("full_name")
    if user.is_active is not True:
        user.is_active = True
        update_fields.append("is_active")
    if user.is_staff is not True:
        user.is_staff = True
        update_fields.append("is_staff")
    if user.is_superuser is not True:
        user.is_superuser = True
        update_fields.append("is_superuser")
    if created:
        user.password = make_password(password)
        update_fields.append("password")
    if update_fields:
        user.save(update_fields=update_fields)

    profile, _ = AdministratorProfile.objects.get_or_create(
        user=user,
        defaults={
            "role": "Superadmin",
            "level": "superadmin",
        },
    )
    profile.role = "Superadmin"
    profile.level = "superadmin"
    profile.created_by = None
    profile.save(update_fields=["role", "level", "created_by"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_administratorprofile_created_by_and_level"),
    ]

    operations = [
        migrations.RunPython(seed_initial_superadmin, migrations.RunPython.noop),
    ]
