# Generated by Django 6.0.4 on 2026-05-11 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_seed_initial_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MFAChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.UUIDField(unique=True)),
                ('code_hash', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('password_reset', 'Password Reset')], max_length=30)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('used', models.BooleanField(default=False)),
                ('revoked', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_mfa_challenges',
                'indexes': [models.Index(fields=['jti'], name='auth_mfa_ch_jti_e4ae20_idx'), models.Index(fields=['expires_at'], name='auth_mfa_ch_expires_062e1c_idx')],
            },
        ),
    ]
