# Generated by Django 6.0.4 on 2026-05-24 01:07

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="cnh",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[apps.users.validators.validate_cnh],
            ),
        ),
    ]
