/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as Admin_rootRouteImport } from './pages/admin/__root'
import { Route as ViagensRouteImport } from './pages/viagens'
import { Route as SignupRouteImport } from './pages/signup'
import { Route as RecoveryRouteImport } from './pages/recovery'
import { Route as LoginRouteImport } from './pages/login'
import { Route as CurrentTripRouteImport } from './pages/current-trip'
import { Route as AdminIndexRouteImport } from './pages/admin/index'
import { Route as AdminBusesRouteImport } from './pages/admin/buses'

const Admin_rootRoute = Admin_rootRouteImport.update({
  id: '/admin/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensRoute = ViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentTripRoute = CurrentTripRouteImport.update({
  id: '/current-trip',
  path: '/current-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBusesRoute = AdminBusesRouteImport.update({
  id: '/admin/buses',
  path: '/admin/buses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/current-trip': typeof CurrentTripRoute
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/signup': typeof SignupRoute
  '/viagens': typeof ViagensRoute
  '/admin': typeof Admin_rootRoute
  '/admin/buses': typeof AdminBusesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/current-trip': typeof CurrentTripRoute
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/signup': typeof SignupRoute
  '/viagens': typeof ViagensRoute
  '/admin': typeof AdminIndexRoute
  '/admin/buses': typeof AdminBusesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/current-trip': typeof CurrentTripRoute
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/signup': typeof SignupRoute
  '/viagens': typeof ViagensRoute
  '/admin/__root': typeof Admin_rootRoute
  '/admin/buses': typeof AdminBusesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/current-trip'
    | '/login'
    | '/recovery'
    | '/signup'
    | '/viagens'
    | '/admin'
    | '/admin/buses'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/current-trip'
    | '/login'
    | '/recovery'
    | '/signup'
    | '/viagens'
    | '/admin'
    | '/admin/buses'
  id:
    | '__root__'
    | '/current-trip'
    | '/login'
    | '/recovery'
    | '/signup'
    | '/viagens'
    | '/admin/__root'
    | '/admin/buses'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CurrentTripRoute: typeof CurrentTripRoute
  LoginRoute: typeof LoginRoute
  RecoveryRoute: typeof RecoveryRoute
  SignupRoute: typeof SignupRoute
  ViagensRoute: typeof ViagensRoute
  Admin_rootRoute: typeof Admin_rootRoute
  AdminBusesRoute: typeof AdminBusesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/__root': {
      id: '/admin/__root'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens': {
      id: '/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof ViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-trip': {
      id: '/current-trip'
      path: '/current-trip'
      fullPath: '/current-trip'
      preLoaderRoute: typeof CurrentTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/buses': {
      id: '/admin/buses'
      path: '/admin/buses'
      fullPath: '/admin/buses'
      preLoaderRoute: typeof AdminBusesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CurrentTripRoute: CurrentTripRoute,
  LoginRoute: LoginRoute,
  RecoveryRoute: RecoveryRoute,
  SignupRoute: SignupRoute,
  ViagensRoute: ViagensRoute,
  Admin_rootRoute: Admin_rootRoute,
  AdminBusesRoute: AdminBusesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
