/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as App_rootRouteImport } from './pages/app/__root'
import { Route as Admin_rootRouteImport } from './pages/admin/__root'
import { Route as SobreProjetoRouteImport } from './pages/sobre-projeto'
import { Route as SignupRouteImport } from './pages/signup'
import { Route as RecuperarRouteImport } from './pages/recuperar'
import { Route as LoginRouteImport } from './pages/login'
import { Route as EquipeRouteImport } from './pages/equipe'
import { Route as IndexRouteImport } from './pages/index'
import { Route as AppIndexRouteImport } from './pages/app/index'
import { Route as AdminIndexRouteImport } from './pages/admin/index'
import { Route as AppViagensRouteImport } from './pages/app/viagens'
import { Route as AdminRotasRouteImport } from './pages/admin/rotas'
import { Route as AdminRelatoriosRouteImport } from './pages/admin/relatorios'
import { Route as AdminOnibusRouteImport } from './pages/admin/onibus'
import { Route as AdminMotoristasRouteImport } from './pages/admin/motoristas'
import { Route as AdminAdminsRouteImport } from './pages/admin/admins'
import { Route as AppDriverViagensRouteImport } from './pages/app/driver/viagens'

const App_rootRoute = App_rootRouteImport.update({
  id: '/app/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_rootRoute = Admin_rootRouteImport.update({
  id: '/admin/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreProjetoRoute = SobreProjetoRouteImport.update({
  id: '/sobre-projeto',
  path: '/sobre-projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppViagensRoute = AppViagensRouteImport.update({
  id: '/app/viagens',
  path: '/app/viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRotasRoute = AdminRotasRouteImport.update({
  id: '/admin/rotas',
  path: '/admin/rotas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOnibusRoute = AdminOnibusRouteImport.update({
  id: '/admin/onibus',
  path: '/admin/onibus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMotoristasRoute = AdminMotoristasRouteImport.update({
  id: '/admin/motoristas',
  path: '/admin/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDriverViagensRoute = AppDriverViagensRouteImport.update({
  id: '/app/driver/viagens',
  path: '/app/driver/viagens',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/signup': typeof SignupRoute
  '/sobre-projeto': typeof SobreProjetoRoute
  '/admin': typeof Admin_rootRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin/onibus': typeof AdminOnibusRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/rotas': typeof AdminRotasRoute
  '/app': typeof App_rootRoute
  '/app/viagens': typeof AppViagensRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/driver/viagens': typeof AppDriverViagensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/signup': typeof SignupRoute
  '/sobre-projeto': typeof SobreProjetoRoute
  '/admin': typeof AdminIndexRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin/onibus': typeof AdminOnibusRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/rotas': typeof AdminRotasRoute
  '/app': typeof AppIndexRoute
  '/app/viagens': typeof AppViagensRoute
  '/app/driver/viagens': typeof AppDriverViagensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/signup': typeof SignupRoute
  '/sobre-projeto': typeof SobreProjetoRoute
  '/admin/__root': typeof Admin_rootRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin/onibus': typeof AdminOnibusRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/rotas': typeof AdminRotasRoute
  '/app/__root': typeof App_rootRoute
  '/app/viagens': typeof AppViagensRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/driver/viagens': typeof AppDriverViagensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipe'
    | '/login'
    | '/recuperar'
    | '/signup'
    | '/sobre-projeto'
    | '/admin'
    | '/admin/admins'
    | '/admin/motoristas'
    | '/admin/onibus'
    | '/admin/relatorios'
    | '/admin/rotas'
    | '/app'
    | '/app/viagens'
    | '/admin/'
    | '/app/'
    | '/app/driver/viagens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equipe'
    | '/login'
    | '/recuperar'
    | '/signup'
    | '/sobre-projeto'
    | '/admin'
    | '/admin/admins'
    | '/admin/motoristas'
    | '/admin/onibus'
    | '/admin/relatorios'
    | '/admin/rotas'
    | '/app'
    | '/app/viagens'
    | '/app/driver/viagens'
  id:
    | '__root__'
    | '/'
    | '/equipe'
    | '/login'
    | '/recuperar'
    | '/signup'
    | '/sobre-projeto'
    | '/admin/__root'
    | '/admin/admins'
    | '/admin/motoristas'
    | '/admin/onibus'
    | '/admin/relatorios'
    | '/admin/rotas'
    | '/app/__root'
    | '/app/viagens'
    | '/admin/'
    | '/app/'
    | '/app/driver/viagens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipeRoute: typeof EquipeRoute
  LoginRoute: typeof LoginRoute
  RecuperarRoute: typeof RecuperarRoute
  SignupRoute: typeof SignupRoute
  SobreProjetoRoute: typeof SobreProjetoRoute
  Admin_rootRoute: typeof Admin_rootRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminMotoristasRoute: typeof AdminMotoristasRoute
  AdminOnibusRoute: typeof AdminOnibusRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminRotasRoute: typeof AdminRotasRoute
  App_rootRoute: typeof App_rootRoute
  AppViagensRoute: typeof AppViagensRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDriverViagensRoute: typeof AppDriverViagensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app/__root': {
      id: '/app/__root'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof App_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/__root': {
      id: '/admin/__root'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-projeto': {
      id: '/sobre-projeto'
      path: '/sobre-projeto'
      fullPath: '/sobre-projeto'
      preLoaderRoute: typeof SobreProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/viagens': {
      id: '/app/viagens'
      path: '/app/viagens'
      fullPath: '/app/viagens'
      preLoaderRoute: typeof AppViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rotas': {
      id: '/admin/rotas'
      path: '/admin/rotas'
      fullPath: '/admin/rotas'
      preLoaderRoute: typeof AdminRotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/onibus': {
      id: '/admin/onibus'
      path: '/admin/onibus'
      fullPath: '/admin/onibus'
      preLoaderRoute: typeof AdminOnibusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/motoristas': {
      id: '/admin/motoristas'
      path: '/admin/motoristas'
      fullPath: '/admin/motoristas'
      preLoaderRoute: typeof AdminMotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/driver/viagens': {
      id: '/app/driver/viagens'
      path: '/app/driver/viagens'
      fullPath: '/app/driver/viagens'
      preLoaderRoute: typeof AppDriverViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipeRoute: EquipeRoute,
  LoginRoute: LoginRoute,
  RecuperarRoute: RecuperarRoute,
  SignupRoute: SignupRoute,
  SobreProjetoRoute: SobreProjetoRoute,
  Admin_rootRoute: Admin_rootRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminMotoristasRoute: AdminMotoristasRoute,
  AdminOnibusRoute: AdminOnibusRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminRotasRoute: AdminRotasRoute,
  App_rootRoute: App_rootRoute,
  AppViagensRoute: AppViagensRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
  AppDriverViagensRoute: AppDriverViagensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
