[tools]
bun = "1.3.12"
python = "3.12" 

 [tasks."docs:api:build"]
description = "Generate the final static HTML documentation"
dir="api"
run = ["poetry run sphinx-apidoc -f -o docs/api .", "poetry run sphinx-build -b html docs docs/_build/html"]

[tasks."docs:api:clean"]
description = "Remove the documentation build directory"
dir="api"
run = "rm -rf docs/_build"

[tasks."docs:api:serve"]
description = "Start the documentation server with hot-reload"
dir="api"
run = "poetry run sphinx-autobuild docs docs/_build/html --watch apps --ignore '**/_build/**'"

[tasks.docs]
description = "Alias for the documentation dev server"
alias = "docs:api:serve"