output-format = "github"
fix = true
preview = true
show-fixes = true
src = ["api", "test"]
target-version = "py312"

exclude = [
  ".git",
  ".venv",
  "__pycache__",
  "**/migrations",
]

[lint]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # import sorting
]

[lint.per-file-ignores]
"api/config/settings/*.py" = ["F403", "F405"]

[format]
docstring-code-format = true
docstring-code-line-length = 60
