# Generated by Django 6.0.6 on 2026-06-19 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_plate', models.CharField(max_length=10, unique=True)),
                ('seating_capacity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENÇÃO', 'Manutenção')], default='ATIVO', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GuestPassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('full_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'trips_guest_passengers',
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('status', models.CharField(choices=[('CANCELAMENTO PARCIAL DO ÔNIBUS', 'Cancelamento Parcial do Ônibus'), ('CANCELADO', 'Cancelado')], default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=50)),
                ('destiny', models.CharField(max_length=50)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_date', models.DateField()),
                ('status', models.CharField(choices=[('RISCO DE CANCELAMENTO', 'Risco de Cancelamento'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('EM ANDAMENTO', 'Em Andamento'), ('CONCLUÍDA', 'Concluída')], default='RISCO DE CANCELAMENTO', max_length=25)),
                ('departure_timestamp', models.DateTimeField(blank=True, null=True)),
                ('arrival_timestamp', models.DateTimeField(blank=True, null=True)),
                ('seating_capacity', models.IntegerField(default=46)),
                ('reserved_seats', models.IntegerField(default=0)),
                ('quorum_met_notified_at', models.DateTimeField(blank=True, null=True)),
                ('quorum_warning_notified_at', models.DateTimeField(blank=True, null=True)),
                ('checkin_started', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripPassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_type', models.CharField(choices=[('LOCAL_SERVER', 'Servidor local'), ('LOCAL_GUEST', 'Convidado local')], default='LOCAL_SERVER', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trips_trip_passengers',
            },
        ),
    ]
