# Generated by Django 6.0.4 on 2026-04-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
