# Generated by Django 6.0.6 on 2026-06-28 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="administrator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.administratorprofile",
            ),
        ),
        migrations.AddField(
            model_name="guestpassenger",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.civilservantprofile",
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="administrator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.administratorprofile",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="administrator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.administratorprofile",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="bus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trips.bus",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.driverprofile",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_trips",
                to="users.civilservantprofile",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trips.route"
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trips.trip"
            ),
        ),
        migrations.AddField(
            model_name="guestpassenger",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trips.trip"
            ),
        ),
        migrations.AddField(
            model_name="trippassenger",
            name="allowed_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_passengers",
                to="users.allowedstaff",
            ),
        ),
        migrations.AddField(
            model_name="trippassenger",
            name="associated_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="associated_local_guests",
                to="users.allowedstaff",
            ),
        ),
        migrations.AddField(
            model_name="trippassenger",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.driverprofile",
            ),
        ),
        migrations.AddField(
            model_name="trippassenger",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_passengers",
                to="trips.trip",
            ),
        ),
        migrations.AddField(
            model_name="triprequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.civilservantprofile",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trips.triprequest",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="guestpassenger",
            unique_together={("cpf", "trip")},
        ),
    ]
