# Generated by Django 6.0.4 on 2026-04-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='number_plate',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
