# Generated by Django 6.0.4 on 2026-05-29 17:38

import apps.trips.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestPassenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=11)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.civilservantprofile",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trips.trip"
                    ),
                ),
            ],
            options={
                "db_table": "trips_guest_passengers",
                "unique_together": {("cpf", "trip")},
            },
            managers=[
                ("objects", apps.trips.models.GuestPassengerManager()),
            ],
        ),
    ]
