# Generated by Django 6.0.6 on 2026-06-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestpassenger",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="max_bus",
            field=models.IntegerField(default=1),
        ),
    ]
