# Generated by Django 6.0.4 on 2026-04-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_bus_number_plate'),
        ('trips', '0002_alter_route_arrival_time_alter_route_departure_time'),
    ]

    operations = [
    ]
