# Generated by Django 6.0.5 on 2026-05-31 21:30

import apps.trips.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="reserved_seats",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trip",
            name="seating_capacity",
            field=models.IntegerField(default=46),
        ),
        migrations.CreateModel(
            name="GuestPassenger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cpf", models.CharField(max_length=11)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.civilservantprofile",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trips.trip"
                    ),
                ),
            ],
            options={
                "db_table": "trips_guest_passengers",
                "unique_together": {("cpf", "trip")},
            },
            managers=[
                ("objects", apps.trips.models.GuestPassengerManager()),
            ],
        ),
    ]
