# Generated by Django 6.0.4 on 2026-04-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_merge_20260426_1101'),
        ('users', '0002_administratorprofile_driverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='brand',
            field=models.CharField(default='Mercedes', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.administratorprofile'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.driverprofile'),
        ),
    ]
