# Generated by Django 6.0.4 on 2026-05-30 01:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_guestpassenger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestpassenger",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
