# Generated by Django 6.0.4 on 2026-05-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_merge_20260426_1101"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrence",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        "CANCELAMENTO PARCIAL DO ÔNIBUS",
                        "Cancelamento Parcial do Ônibus",
                    ),
                    ("CANCELADO", "Cancelado"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("RISCO DE CANCELAMENTO", "Risco de Cancelamento"),
                    ("CONFIRMADA", "Confirmada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="CONFIRMADA",
                max_length=25,
            ),
        ),
    ]
