# Generated by Django 6.0.4 on 2026-05-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_alter_guestpassenger_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="seating_capacity",
            field=models.IntegerField(default=46),
        ),
    ]
