# Generated by Django 6.0.4 on 2026-05-08 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_alter_occurrence_status_alter_trip_status"),
        ("trips", "0004_bus_brand_alter_bus_administrator_alter_bus_driver"),
    ]

    operations = []
