# Generated by Django 6.0.5 on 2026-05-31 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_guestpassenger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippassenger',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_passengers', to='trips.trip'),
        ),
    ]
