# Generated by Django 6.0.4 on 2026-05-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_trip_seating_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="reserved_seats",
            field=models.IntegerField(default=0),
        ),
    ]
