# Generated by Django 6.0.4 on 2026-05-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_merge_20260508_0126"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("RISCO DE CANCELAMENTO", "Risco de Cancelamento"),
                    ("CONFIRMADA", "Confirmada"),
                    ("CANCELADA", "Cancelada"),
                    ("EM ANDAMENTO", "Em Andamento"),
                    ("CONCLUÍDA", "Concluída"),
                ],
                default="CONFIRMADA",
                max_length=25,
            ),
        ),
    ]
