# Generated by Codex on 2026-06-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_alter_trippassenger_trip"),
        ("trips", "0006_trip_reserved_seats"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trippassenger",
            name="allowed_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_passengers",
                to="users.allowedstaff",
            ),
        ),
        migrations.AddField(
            model_name="trippassenger",
            name="passenger_type",
            field=models.CharField(
                choices=[
                    ("LOCAL_SERVER", "Servidor local"),
                    ("LOCAL_GUEST", "Convidado local"),
                ],
                default="LOCAL_SERVER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trippassenger",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="trippassenger",
            name="cpf",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="trippassenger",
            name="associated_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="associated_local_guests",
                to="users.allowedstaff",
            ),
        ),
    ]
