# Generated by Django 6.0.4 on 2026-05-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_alter_trip_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("RISCO DE CANCELAMENTO", "Risco de Cancelamento"),
                    ("CONFIRMADA", "Confirmada"),
                    ("CANCELADA", "Cancelada"),
                    ("EM ANDAMENTO", "Em Andamento"),
                    ("CONCLUÍDA", "Concluída"),
                ],
                default="RISCO DE CANCELAMENTO",
                max_length=25,
            ),
        ),
    ]
