# Generated by Django 6.0.4 on 2026-05-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_trip_driver_alter_trip_bus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="driver",
        ),
    ]
