# Generated by Django 6.0.4 on 2026-05-24 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_alter_trip_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="bus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trips.bus",
            ),
        ),
    ]
