# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_local_trip_passengers"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="quorum_met_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="quorum_warning_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
