# Generated by Django 6.0.5 on 2026-06-25 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_trip_quorum_notifications"),
        ("users", "0002_customuser_deleted_at_customuser_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="access_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trip",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_trips",
                to="users.civilservantprofile",
            ),
        ),
        migrations.CreateModel(
            name="TripRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_text", models.CharField(max_length=255)),
                ("destiny_text", models.CharField(max_length=255)),
                ("departure_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("return_time", models.TimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADA", "Aprovada"),
                            ("RECUSADA", "Recusada"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.civilservantprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trips.triprequest",
            ),
        ),
    ]
