# Generated by Django 6.0.6 on 2026-06-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_trip_quorum_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="max_bus",
            field=models.IntegerField(default=1),
        ),
    ]
