# Generated by Django 6.0.4 on 2026-05-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_alter_trip_bus"),
        ("trips", "0008_remove_bus_driver"),
    ]

    operations = []
