# Generated by Django 6.0.6 on 2026-06-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0009_route_max_bus"),
        ("trips", "0009_trip_access_code_trip_is_private_trip_manager_and_more"),
    ]

    operations = []
