# Generated by Django 6.0.4 on 2026-05-24 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0009_merge_0008_alter_trip_bus_0008_remove_bus_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="bus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trips.bus",
            ),
        ),
    ]
