# Generated by Django 6.0.6 on 2026-06-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0010_merge_20260628_1708"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestpassenger",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
