# Generated by Django 6.0.4 on 2026-05-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0011_trippassenger"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="status",
            field=models.CharField(
                choices=[("ATIVO", "Ativo"), ("MANUTENÇÃO", "Manutenção")],
                default="ATIVO",
                max_length=25,
            ),
        ),
    ]
