# Generated by Django 6.0.6 on 2026-06-19 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkin_date', models.DateTimeField(blank=True, null=True)),
                ('check_in', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('LISTA SECUNDÁRIA', 'Lista Secundária')], default='PENDENTE', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
