# Generated by Django 6.0.4 on 2026-05-29 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        ("trips", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="civil_servant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.civilservantprofile",
            ),
        ),
        migrations.AddField(
            model_name="punishment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.studentprofile"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="civil_servant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.civilservantprofile",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trips.trip"
            ),
        ),
        migrations.AddField(
            model_name="punishment",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="reservations",
            field=models.ManyToManyField(to="reservations.reservation"),
        ),
    ]
