# Generated by Django 6.0.4 on 2026-05-17 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="queue_position",
        ),
        migrations.AddField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
