# Generated by Django 6.0.6 on 2026-06-28 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        ("trips", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="civil_servant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.civilservantprofile",
            ),
        ),
        migrations.AddField(
            model_name="punishment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.studentprofile"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="civil_servant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.civilservantprofile",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="guest_passenger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trips.guestpassenger",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trips.trip"
            ),
        ),
        migrations.AddField(
            model_name="punishment",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="reservations",
            field=models.ManyToManyField(
                related_name="guests", to="reservations.reservation"
            ),
        ),
    ]
