# Generated by Django 6.0.4 on 2026-05-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="punishment",
            name="value",
        ),
        migrations.AddField(
            model_name="punishment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
