# Generated by Django 6.0.4 on 2026-05-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_remove_reservation_queue_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
