# Generated by Django 6.0.4 on 2026-05-29 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_remove_punishment_value_punishment_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="punishment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
