# Generated by Django 6.0.5 on 2026-05-31 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_punishment_created_at"),
        ("trips", "0003_trip_reserved_seats_trip_seating_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="guest_passenger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trips.guestpassenger",
            ),
        ),
    ]
